// ELECTRONICS
export const BUY_PHONE = "BUY_PHONE";
export const BUY_TABLET = "BUY_TABLET";
export const BUY_TV = "BUY_TV";

// APPLIANCES
export const BUY_COOLER = "BUY_COOLER";

// COMMENTS_LOADING
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_LOADING_SUCCESS = 'COMMENTS_LOADING_SUCCESS';
export const COMMENTS_LOADING_ERROR = 'COMMENTS_LOADING_ERROR';
